### ISSUE TITLE
"We're all adults." vs. kids in opensource

### ISSUE THREAD

**Issue by ri0t** [domgetter/NCoC#19]
First of all: thanks for the NCoC!

But then again, i'm unsure about the phrase "We're all adults." - generally, i totally accept that notion, but alas, we're not all adults. E.g. I demo'ed my project to a very enthusiastic 13 year old recently, whose contributions I verily look forward to.

Then again, well, some kids are obviously more adult than many adults

Am i too sensitive, here or can we find a better wording?

**Comment by optomal7** [comment]
Maybe the phrase could be reoriented to say "We're all expected to treat each other as though we are all adults."

**Comment by BenMcLean** [comment]
I say drop the reference to adults and instead refer to maturity

**Comment by domgetter** [comment]
The phrase "we're all adults" basically means "we're all capable of acting like reasonable, rational people in virtual, open source spheres".

I feel like making the statement longer for clarity is not a good trade-off.  The NCoC was created as a response to these elaborate, verbose, authoritarian codes of conduct, and the brevity in the NCoC is, in and of itself, a response to the nature of those codes of conduct.  Basically, we're stating "we don't need to explain in excruciating detail all the acceptable and unacceptable behaviors in maintaining and contributing to open source projects".  It's a response to the implication that open source is filled with socially inept, childish actors, and that they need to be "educated" and informed on unacceptable social behavior.

It does not mean that people under 18 are excluded from participating (or some other objective, arbitrary definition of adult).

As for changing the wording to "maturity" instead of "adult", I feel like those mean basically the same thing in this context, and we don't really gain anything from changing it.

> I demo'ed my project to a very enthusiastic 13 year old recently, whose contributions I verily look forward to.

And did this person appear apprehensive on contributing because of the wording of the code of conduct?  If so, that may be a practical argument on changing the specific wording.

I would be happy to add a question in the FAQ which explains that "adult" doesn't mean "non-teenagers".

What are your thoughts on this?

**Comment by teo-tsirpanis** [comment]
In my projects, I use [this variation](https://github.com/teo-tsirpanis/Farkle/blob/master/CODE_OF_CONDUCT.md).

**Comment by jorgecc** [comment]
Legally, kids can't work because it is child labor and it's illegal. So, if they want to "collaborate" (work without payment) then, they should do it under the supervision of an adult.

**Comment by taradinoc** [comment]
>Legally, kids can't work because it is child labor and it's illegal. 

Not true at all.

The laws vary by jurisdiction, but teenagers as young as 15 can generally work for pay, legally, although they might have restricted hours or might need to get a work permit.

But those labor laws are about working for pay. There's nothing stopping a minor from contributing code to an open source project with no employment relationship.

**Comment by tonymorris** [comment]
Yeah, both my (programmer) children would be onboard with this project if they knew of it.

I would suggest something like, "even children can successfully socialise without intervention by a Code of Conduct!"

**Comment by tonymorris** [comment]
Minimum age for child labour is 13 years in Australia. Most places won't employ you until you are 14.

**Comment by domgetter** [comment]
As I stated above, this has nothing to do with age.

If you want to modify the NCoC for your own use, like @teo-tsirpanis, you are more than welcome to do so.

Thank you everyone for your feedback.

**Comment by binex-dsk** [comment]
> Legally, kids can't work because it is child labor and it's illegal. So, if they want to "collaborate" (work without payment) then, they should do it under the supervision of an adult.

that would be a looooooooot of explaining to my dad that I don't want

**Comment by yisraeldov** [comment]
In what country is it completely illegal for kids to work? In all
countries that I know of you don't have to be a legal adult to be
employed.

"The Fair Labor Standards Act (FLSA) sets 14 as the minimum age for
most non-agricultural work. However, at any age, youth may deliver
newspapers; perform in radio, television, movie, or theatrical
productions; work in businesses owned by their parents (except in
mining, manufacturing or hazardous jobs); and perform babysitting or
perform minor chores around a private home. Also, at any age, youth may
be employed as homeworkers to gather evergreens and make evergreen
wreaths."

https://webapps.dol.gov/elaws/faq/esa/flsa/026.htm

**Comment by ghost** [comment]
Ok i think we can all agree on this: being an "adult" means not being Coraline Ada
