### ISSUE TITLE
I am 15 years old

### ISSUE THREAD

**Issue by EdvinVikstrom** [domgetter/NCoC#42]
Not everyone are adults:(

**Comment by matthieuriolo** [comment]
But I guess it would make sense if you would get treated like one. At least in the context of open source. Or do you think there is a necessity to have a specific section which deals with children?

**Comment by EdvinVikstrom** [comment]
it looks like the person that wrote the COC thinks only adults can program :( But whatever ;) i am an adult in a few years O
          /|\
          /\

**Comment by domgetter** [comment]
See #19

**Comment by matthieuriolo** [comment]
@Ficklampan 

1) According to us, yes, yes you are allowed to participate and we are aware that youngsters can program too - we used to be one of them 😝 we didnt exclude you. We are just trying to describe the behavior we expect from you

2) There are variety of people who can program and are poorly described by the word "adult". As domgetter points out in the other ticket, we dont want a lengthy but juridical correct CoC. In fact, we dont want a CoC at all. But since we sorta are forced to have one, we trimmed it down to something useful and sensible. No weird list of DONTs, no weird list of DOs etc.

3) Feel free do adapt the NCoC and change it in a way which you thinks it suits you the best. You are not forced to stick to the original NCoC. You are allowed to adapt it in anyway you want

4) If a project uses the NCoC and you are not sure if you are allowed to participate, feel free to ask the maintainer if it's okay when you participate
